site_name: Command-line tutorial&nbsp;&nbsp;
repo_url: "https://github.com/compgen-io/cmdline-tutorial"
pdf_url: "pdf/cmdline-tutorial.pdf"

theme:
    name: null
    custom_dir: 'cinder/cinder'
extra_css:
  - "css/style.css"

# theme: material

        #  name: bootstrap4
#  name: material
#  palette:
#    primary: 'blue grey'
#    accent: 'light blue'
#  font:
#    text: 'Helvetica'
#    code: 'Menlo'
nav:
       - Command-line:
          - Welcome: 'index.md'
          - 'Unix concepts': 'cmd/concepts.md'
          - 'Terminal / SSH': 'cmd/terminal.md'
          - 'Common commands': 'cmd/common.md'
          - 'Tranferring data': 'cmd/transfer.md'
          - 'Customizing the shell': 'cmd/customizing.md'
          - 'Writing scripts': 'cmd/scripts.md'
          - 'Data pipelines': 'cmd/02-Data_Processing.md'
          - 'Links': 'cmd/otherlinks.md'

       - Git: 'git/index.md'
       - Cluster jobs: 'clusters/index.md'

markdown_extensions:
  - toc:
          permalink: []
          toc_depth: "1-3"
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search:
        prebuilt_index: 'python'
        #    - pdf-export:
        #verbose: true
        #combined: true
        #media_type: print
        #enabled_if_env: ENABLE_PDF_EXPORT
        #combined_output_path: pdf/cmdline-tutorial.pdf

